<a href="https://colab.research.google.com/github/DiyaBansal0325/training-python/blob/main/Day_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Data Science
# Understand Problem => Data acquire => Data Pre-process => Data storage =>
# Data Preperation (to extract that info) => Data Analysis => Data Visualize
# Ml and Algorithms (chatbot , open ai services , open CV , NLP) => Data report

In [ ]:
# Python => libraries => Pandas and Numpy(2 libraries we will be using to acquire data and to pre-process data)
# numpy => numerical python -> used to prepare data in form of number
# numpy is an scientific library in which data is stored in form of nD array
# to work on numpy we will import numpy

In [ ]:
import numpy
numpy.arange(4)

array([0, 1, 2, 3])

In [ ]:
import numpy
type( numpy.arange(7) )

numpy.ndarray

In [ ]:
import numpy as np
arr1 = np.arange(5)
arr1

array([0, 1, 2, 3, 4])

In [ ]:
arr1 = np.array([10,20,30,40])
print(arr1.size)
print(arr1.shape)

4
(4,)


In [ ]:
arr1 = np.array( [[1,2] , [3,4] , [5,6] ] )
print(arr1.size)
print(arr1.shape)
print(arr1.dtype)

6
(3, 2)
int64


In [ ]:
np.ndarray(3)

array([0. , 0.5, 1. ])

In [ ]:
arr2 = np.arange(3)
print(arr2.shape)

(3,)


In [ ]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr1 = np.arange(9)
print(arr1)
print(arr1.reshape(3,3))

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
import numpy as np
a = np.array( [ [1,2] , [3,4] ] )
print(a)


[[1 2]
 [3 4]]


In [ ]:
b = a.transpose()
print(b)

[[1 3]
 [2 4]]


In [ ]:
import numpy as np
a = np.array([ [[1,2] , [4,5], [7,8]] ])
print(a)
print(a.ndim)
print(a.shape)

[[[1 2]
  [4 5]
  [7 8]]]
3
(1, 3, 2)


In [ ]:
b = a.transpose()
print(b)

[[[1]
  [4]
  [7]]

 [[2]
  [5]
  [8]]]


In [ ]:
#numpy => converting string into int

In [ ]:
#pandas: powerful => to data transform , clean , prepare it according to our requirement
#Series => 1D array
#Dataframe : collection of series (kind of tabular format for our data)

In [ ]:
import pandas
sr1 = pandas.Series( [10,2,34,4])
sr1.values

array([10,  2, 34,  4])

In [ ]:
sr1.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
print(sr1[0])

10


In [ ]:
import pandas
sr1 = pandas.Series( [10,2,34,4])
sr1[0] = 60 #Update
sr1[5] = 100  #Insert
sr1

0     60
1      2
2     34
3      4
5    100
dtype: int64

In [ ]:
sr1.max()

100

In [ ]:
sr1.min()

2

In [ ]:
print(sr1.idxmax())  #tells us on which index max value is

5


In [ ]:
print(sr1.idxmin())  #tells us on which index min value is

1


In [ ]:
#Series with customize index
import pandas as pd
sr1 = pd.Series( [10,2,34,4], index=['A','B','C','D'])
sr1

A    10
B     2
C    34
D     4
dtype: int64

In [ ]:
sr1.to_dict()  #To show series in form of list

{'A': 10, 'B': 2, 'C': 34, 'D': 4}

In [ ]:
arr = np.array( [10,13,15,19,24] )
sr1 = pd.Series( arr )
sr1

0    10
1    13
2    15
3    19
4    24
dtype: int64

In [ ]:
type(sr1)

pandas.core.series.Series

In [ ]:
arr = np.array( [10,13,15,10,15] )
sr1 = pd.Series( arr )
sr1.value_counts()  #Count the no of times a value comes

10    2
15    2
13    1
Name: count, dtype: int64

In [ ]:
sr1.value_counts(ascending = False)   #By default

10    2
15    2
13    1
Name: count, dtype: int64

In [ ]:
sr1.value_counts(ascending = True)

13    1
10    2
15    2
Name: count, dtype: int64

In [ ]:
arr = np.array( [10,13,15] )
sr1 = pd.Series( arr )
sr1.is_unique   #tells whether all elements are unique or not

True

In [ ]:
arr = np.array( [10,13,15] )
sr1 = pd.Series( arr )
sr1.nunique()    #tells total unique elements

3

In [ ]:
sr1 = pd.Series( [1,52,14,9,10,45,11] )
sr1.sort_values(ascending = False)

1    52
5    45
2    14
6    11
4    10
3     9
0     1
dtype: int64

In [ ]:
sr1.sort_values(ascending = True)   #By default

0     1
3     9
4    10
6    11
2    14
5    45
1    52
dtype: int64

In [ ]:
arr = np.array( [10,13,15,92,15,14] )
sr1 = pd.Series( arr )
sr1.drop_duplicates()     #Removes the duplicate values without changing original series

0    10
1    13
2    15
3    92
5    14
dtype: int64

In [ ]:
sr1

0    10
1    13
2    15
3    92
4    15
5    14
dtype: int64

In [ ]:
arr = np.array( [10,13,15,92,15,14] )
sr1 = pd.Series( arr )
sr1.drop_duplicates(inplace = True)  #this removes duplicates from original series too

In [ ]:
sr1

0    10
1    13
2    15
3    92
5    14
dtype: int64

In [ ]:
dict = {"A":10,"B":6,"C":95,"D":5,"E":10}
sr2 = pd.Series(dict)
sr2

A    10
B     6
C    95
D     5
E    10
dtype: int64

In [ ]:
sr2.value_counts()

10    2
6     1
95    1
5     1
Name: count, dtype: int64

In [ ]:
sr2.max()

95

In [ ]:
sr2.min()

5

In [ ]:
sr2.idxmax()

'C'

In [ ]:
sr2.idxmin()

'D'

In [ ]:
sr2.nunique()

4

In [ ]:
sr2.sort_values()

D     5
B     6
A    10
E    10
C    95
dtype: int64

In [ ]:
sr2.drop_duplicates()

A    10
B     6
C    95
D     5
dtype: int64

In [ ]:
data = [ [10,12,13] , [14,15,16] , [17,18,19] ]
pd.DataFrame(data)

0   1   2
0  10  12  13
1  14  15  16
2  17  18  19

In [ ]:
df = pd.DataFrame(data, columns=["prd1","prd2","prd3"])
df
type(df)

pandas.core.frame.DataFrame

In [ ]:
type(df["prd1"])

pandas.core.series.Series

In [ ]:
#Read a csv file in pandas and select one column and count how many time the value is present here and find top 3 values
#Count how many no of unique values we have
#Drop the duplicate values from column
#Change the int column to float